# This is a basic workflow to help you get started with Actions

name: Publish

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  # We want to hook up the mindersec/minder repo to trigger this action
  # on pushes to the main branch under docs.
  workflow_dispatch:

jobs:
  build:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest

    permissions:
      contents: read

    defaults:
      run:
        working-directory: ./docs
    steps:
      - name: Checkout docs
        uses: actions/checkout@v4
        with:
          repository: mindersec/minder

      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build website
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/build
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      pages: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
